minimumReleaseAge: 10080
shellEmulator: true

trustPolicy: no-downgrade
blockExoticSubdeps: true
allowBuilds:
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: true

overrides:
  '@types/vscode': ~1.95.0
  semver: ^7.8.5
