blockExoticSubdeps: true
minimumReleaseAge: 10080
minimumReleaseAgeExcludePrune: true
trustPolicy: no-downgrade
shellEmulator: true

overrides:
  '@types/vscode': ~1.95.0
  semver: ^7.8.5

allowBuilds:
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: true
